#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-nocasedict
Version  : 1.1.0
Release  : 31
URL      : https://files.pythonhosted.org/packages/e2/a7/cbbda960e7adac9eeceed1ad8ab6ace018a8a700c216cccbbc2c94e7bbe7/nocasedict-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e2/a7/cbbda960e7adac9eeceed1ad8ab6ace018a8a700c216cccbbc2c94e7bbe7/nocasedict-1.1.0.tar.gz
Summary  : A case-insensitive ordered dictionary for Python
Group    : Development/Tools
License  : LGPL-2.1
Requires: pypi-nocasedict-license = %{version}-%{release}
Requires: pypi-nocasedict-python = %{version}-%{release}
Requires: pypi-nocasedict-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(six)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
nocasedict - A case-insensitive ordered dictionary for Python
=============================================================

%package license
Summary: license components for the pypi-nocasedict package.
Group: Default

%description license
license components for the pypi-nocasedict package.


%package python
Summary: python components for the pypi-nocasedict package.
Group: Default
Requires: pypi-nocasedict-python3 = %{version}-%{release}

%description python
python components for the pypi-nocasedict package.


%package python3
Summary: python3 components for the pypi-nocasedict package.
Group: Default
Requires: python3-core
Provides: pypi(nocasedict)
Requires: pypi(six)

%description python3
python3 components for the pypi-nocasedict package.


%prep
%setup -q -n nocasedict-1.1.0
cd %{_builddir}/nocasedict-1.1.0
pushd ..
cp -a nocasedict-1.1.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674350278
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-nocasedict
cp %{_builddir}/nocasedict-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nocasedict/b386b371ce94933e63ced1052aa72a60da5485ff || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-nocasedict/b386b371ce94933e63ced1052aa72a60da5485ff

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
